object_type:
  name: users
  storage: mysql
  deletion: directly_only
  id: email
  id_type: string
  edge_types: []
#     - name: waddup
#       to:
#         object_type: answers
#         field: email
#       deletion: deep
---
  object_type:
    name: answers
    storage: mysql
    deletion: directly_only
#    x:
#      - users
    id: email
    edge_types: []
---
  object_type:
    name: lectures
    storage: mysql
    deletion: directly_only
    id: id
    edge_types: []
#       - name: waddup
#         to:
#           object_type: questions
#           field: lec
#         deletion: deep
---
  object_type:
    name: questions
    storage: mysql
    deletion: directly_only
#    x:
#     - lectures
    id: lec_q_id
    edge_types: []
      # - name: question_to_answer
      #   to:
      #     object_type: answers
      #     field: questionToAnswerId
      #   deletion: deep
---
object_type:
    name: lectures_test
    storage: mysql
    deletion: directly
    id: id
#    id_type: string
    edge_types:
       - name: lectToQuestion
         from_id_type: number
         to:
           object_type: questions_test
           field: lec_id
         deletion: deep
---
object_type:
    name: questions_test
    storage: mysql
    deletion: by_x_only
    x:
     - lectToQuestion
    id: q_id
    edge_types:
       - name: questionToAnswers
         from_id_type: number
         to:
           object_type: answers_test
           field: q_id
         deletion: deep
---
object_type:
    name: answers_test
    storage: mysql
    deletion: by_x_only
    x:
     - questionToAnswers
     - userToAnswers
    id: q_id
    edge_types: []
---
object_type:
    name: users_test
    storage: mysql
    deletion: directly_only
    id: email
    id_type: string
    edge_types:
        - name: userToAnswers
          from_id_type: string
          to:
            object_type: answers_test
            field: u_email
          deletion: deep
