object_type:
    name: lectures
    storage: mysql
    deletion: directly
    id: id
    edge_types:
       - name: lectureToQuestions
         from_id_type: number
         to:
           object_type: questions
           field: lec_id
         deletion: deep
---
object_type:
    name: questions
    storage: mysql
    deletion: directly
    id: q_id
    edge_types:
       - name: questionToAnswers
         from_id_type: number
         to:
           object_type: answers
           field: q_id
         deletion: deep
---
object_type:
    name: answers
    storage: mysql
    deletion: by_x_only
    x:
     - questionToAnswers
     - userToAnswers
    id: q_id
    edge_types: []
---
object_type:
    name: users
    storage: mysql
    deletion: directly_only
    id: email
    id_type: string
    edge_types:
        - name: userToAnswers
          from_id_type: string
          to:
            object_type: answers
            field: u_email
          deletion: deep
